# Generated by Django 5.2.6 on 2025-09-07 10:25

import cloudinary.models
import product.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[product.validators.validate_file_size],
                verbose_name="image",
            ),
        ),
    ]
