# Generated by Django 5.2.6 on 2025-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image_alter_product_name_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube video URL here. Example: https://www.youtube.com/watch?v=xxxxxx', null=True),
        ),
    ]
