# Generated by Django 5.2.6 on 2025-09-06 20:46

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_review_image_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/images', validators=[product.validators.validate_file_size]),
        ),
    ]
