# Generated by Django 5.2.6 on 2025-09-07 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
        ("product", "0007_alter_reviewimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="product.product"
            ),
        ),
    ]
