# Generated by Django 5.2.6 on 2025-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartitem_quantity_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=24.3, max_digits=10),
            preserve_default=False,
        ),
    ]
